_1: &root_dir "./data/ILSVRC2012_img_val"
_2: &backbone_ckpt "./ckpt/dinov2_vitg14_pretrain.pth"
#_2: &backbone_ckpt "./ckpt/condense_vitg14.pth"
_3: &head_ckpt "./ckpt/dinov2_vitg14_imagenet_linear_head.pth"
#_3: &head_ckpt "./ckpt/condense_vitg14_imagenet_linear_head.pth"


debug: false
exp_name: "cls_imagenet_eval"

backbone:
  name: "dinov2_vitg14"
  ckpt: *backbone_ckpt

head:
  ckpt: *head_ckpt

dataset:
  name: "imagenet"
  root: *root_dir
  n_classes: 1000
  imagenet:
    test_ground_truth: !join [ *root_dir, /ILSVRC2012_val_labels.txt ]

classification:
  test_image_size: [224, 224]
